name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'android_keystore.jks'
#        fileDir: '/home/runner/work/<<project name>>/<<project name>>/app/keystore/'
        fileDir: '/home/runner/work/CICD-Example/CICD-Example/app/keystore/'
        encodedString: ${{secrets.KEY_STORE}}
#    - name: Build with Gradle
#      run: ./gradlew build
    - name: Build sign apk
      run: ./gradlew assembleBeta
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    - name: upload to firebase app distribution
      uses:  wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: qa,qa2
#        file: app/build/outputs/apk/release/<<application name>>_${{ github.event.inputs.version }}.apk
#        file: app/build/outputs/apk/release/app-release.apk
        file: app/build/outputs/apk/beta/app-beta.apk
#        file: app/build/outputs/apk/debug/app-debug.apk
